import { z } from "zod";
import type { CognitiveWorkspaceService } from "../cognitive/cognitive-workspace-service.js";
import { defineCapability } from "./schema.js";

const unit=z.number().min(0).max(1);
export function cognitiveCapabilities(service:CognitiveWorkspaceService){return[
  defineCapability({id:"cognitive.workspace.list",version:"1.0.0",description:"List durable Global Workspace cognitive objects ordered by attention priority.",risk:"pure",sideEffect:false,source:"core"},z.object({attentionState:z.enum(["queued","focused","deferred"]).optional()}),async(input,ctx)=>({objects:await service.objects(ctx.tenantId,input.attentionState)})),
  defineCapability({id:"cognitive.object.create",version:"1.0.0",description:"Create a sourced, confidence/importance-scored cognitive object without automatically executing it.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({sessionId:z.string().optional(),kind:z.enum(["observation","problem","hypothesis","insight","risk","opportunity","decision"]),title:z.string().min(1).max(500),content:z.string().min(1).max(100000),sourceType:z.enum(["user","agent","event","memory","system"]),sourceId:z.string().max(500).optional(),confidence:unit,importance:unit,urgency:unit,impact:unit,userRelevance:unit,horizon:z.enum(["reactive","tactical","strategic"]),goalId:z.string().optional(),requestedTokens:z.number().int().min(100).max(10000000).optional(),requestedTimeMs:z.number().int().min(1000).optional(),tags:z.array(z.string()).max(100).optional(),relations:z.array(z.string()).max(200).optional()}),async(i,ctx)=>await service.createObject({tenantId:ctx.tenantId,kind:i.kind,title:i.title,content:i.content,sourceType:i.sourceType,confidence:i.confidence,importance:i.importance,urgency:i.urgency,impact:i.impact,userRelevance:i.userRelevance,horizon:i.horizon,...(i.sessionId?{sessionId:i.sessionId}:{}),...(i.sourceId?{sourceId:i.sourceId}:{}),...(i.goalId?{goalId:i.goalId}:{}),...(i.requestedTokens!==undefined?{requestedTokens:i.requestedTokens}:{}),...(i.requestedTimeMs!==undefined?{requestedTimeMs:i.requestedTimeMs}:{}),...(i.tags?{tags:i.tags}:{}),...(i.relations?{relations:i.relations}:{})})),
  defineCapability({id:"cognitive.attention.allocate",version:"1.0.0",description:"Allocate bounded Global Workspace focus by constitutional goal class, score, token budget and focus slots.",risk:"privileged",sideEffect:true,source:"core"},z.object({}),async(_i,ctx)=>await service.allocateAttention(ctx.tenantId)),
  defineCapability({id:"cognitive.iteration.record",version:"1.0.0",description:"Record a hash-only thought iteration and block the object after repeated identical outcomes.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({objectId:z.string(),result:z.string().min(1).max(100000)}),async(i,ctx)=>await service.recordIteration(ctx.tenantId,i.objectId,i.result)),
  defineCapability({id:"cognitive.goals.list",version:"1.0.0",description:"List constitutional P0-P4 cognitive goals.",risk:"pure",sideEffect:false,source:"core"},z.object({}),async(_i,ctx)=>({goals:await service.goals(ctx.tenantId)})),
  defineCapability({id:"cognitive.goal.create",version:"1.0.0",description:"Create a bounded constitutional cognitive goal. P0/P1 authority remains policy-gated.",risk:"privileged",sideEffect:true,source:"core"},z.object({title:z.string().min(1).max(300),objective:z.string().min(1).max(10000),class:z.enum(["P0","P1","P2","P3","P4"]),importance:unit,urgency:unit,userRelevance:unit}),async(i,ctx)=>await service.createGoal({tenantId:ctx.tenantId,...i})),
  defineCapability({id:"cognitive.goals.arbitrate",version:"1.0.0",description:"Rank active goals by constitutional class before importance, urgency and user relevance, preserving close conflicts.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({}),async(_i,ctx)=>await service.arbitrateGoals(ctx.tenantId)),
  defineCapability({id:"cognitive.mode.get",version:"1.0.0",description:"Read the tenant cognitive operating mode and transition history.",risk:"pure",sideEffect:false,source:"core"},z.object({}),async(_i,ctx)=>await service.mode(ctx.tenantId)),
  defineCapability({id:"cognitive.mode.transition",version:"1.0.0",description:"Apply a constitution-checked cognitive mode transition with a durable reason.",risk:"privileged",sideEffect:true,source:"core"},z.object({mode:z.enum(["reactive","research","development","reflection","dream","emergency"]),reason:z.string().min(1).max(1000)}),async(i,ctx)=>await service.transitionMode(ctx.tenantId,i.mode,i.reason)),
];}
