import { z } from "zod";
import type { AgentSocietyService } from "../society/agent-society-service.js";
import { defineCapability } from "./schema.js";

const priority = z.enum(["critical", "high", "normal", "low"]);
export function societyCapabilities(service: AgentSocietyService) {
  return [
    defineCapability({ id: "society.roles.list", version: "1.0.0", description: "List the tenant's Aurora council, specialist and micro-agent roles with reputation and capability tags.", risk: "pure", sideEffect: false, source: "core" }, z.object({}), async (_input, context) => ({ roles: await service.roles(context.tenantId) })),
    defineCapability({ id: "society.tasks.list", version: "1.0.0", description: "List durable society marketplace tasks and bids.", risk: "pure", sideEffect: false, source: "core" }, z.object({}), async (_input, context) => ({ tasks: await service.tasks(context.tenantId) })),
    defineCapability({ id: "society.task.post", version: "1.0.0", description: "Post a bounded task to the Aurora society marketplace. This mutates durable orchestration state.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ rootSessionId: z.string(), title: z.string().min(1).max(300), objective: z.string().min(1).max(50_000), requiredCapabilityTags: z.array(z.string()).max(100).default([]), priority: priority.default("normal"), maxTokens: z.number().int().min(100).max(10_000_000).default(100_000), deadline: z.string().datetime().optional() }), async (input, context) => await service.postTask({ tenantId: context.tenantId, rootSessionId: input.rootSessionId, title: input.title, objective: input.objective, requiredCapabilityTags: input.requiredCapabilityTags, priority: input.priority, maxTokens: input.maxTokens, ...(input.deadline ? { deadline: input.deadline } : {}) })),
    defineCapability({ id: "society.task.bid", version: "1.0.0", description: "Submit one role bid with confidence and resource estimate to an open society task.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string(), roleId: z.string(), confidence: z.number().min(0).max(1), estimatedTokens: z.number().int().positive(), estimatedDurationMs: z.number().int().positive(), rationale: z.string().min(1).max(2000) }), async (input, context) => await service.bid({ tenantId: context.tenantId, ...input })),
    defineCapability({ id: "society.task.award", version: "1.0.0", description: "Deterministically award a marketplace task under reputation, capability, cost and tenant budget rules.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string() }), async ({ taskId }, context) => await service.award(context.tenantId, taskId)),
    defineCapability({ id: "society.task.execute", version: "1.0.0", description: "Spawn the awarded profile-bound specialist as an isolated child session. Policy authority cannot exceed the parent.", risk: "privileged", sideEffect: true, source: "core" }, z.object({ taskId: z.string() }), async ({ taskId }, context) => await service.execute(context.tenantId, taskId)),
    defineCapability({ id: "society.deliberations.list", version: "1.0.0", description: "List multi-role deliberations, perspectives, dissent and weighted outcomes.", risk: "pure", sideEffect: false, source: "core" }, z.object({}), async (_input, context) => ({ deliberations: await service.deliberations(context.tenantId) })),
    defineCapability({ id: "society.deliberation.create", version: "1.0.0", description: "Open a bounded multi-role deliberation with an explicit quorum.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ question: z.string().min(1).max(10_000), requiredRoleIds: z.array(z.string()).min(2).max(50), quorum: z.number().int().min(2).optional() }), async (input, context) => await service.createDeliberation({ tenantId: context.tenantId, question: input.question, requiredRoleIds: input.requiredRoleIds, ...(input.quorum !== undefined ? { quorum: input.quorum } : {}) })),
    defineCapability({ id: "society.deliberation.submit", version: "1.0.0", description: "Submit one role perspective with recommendation, confidence, rationale and evidence IDs.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ deliberationId: z.string(), roleId: z.string(), recommendation: z.enum(["approve", "reject", "abstain"]), confidence: z.number().min(0).max(1), summary: z.string().min(1).max(10_000), evidenceEventIds: z.array(z.string()).max(200).default([]) }), async (input, context) => await service.submitPerspective({ tenantId: context.tenantId, ...input })),
    defineCapability({ id: "society.deliberation.resolve", version: "1.0.0", description: "Resolve a quorum deliberation by reputation/confidence weight while preserving dissent and missing perspectives.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ deliberationId: z.string() }), async ({ deliberationId }, context) => await service.resolveDeliberation(context.tenantId, deliberationId)),
  ];
}
